### ISSUE TITLE
Unnecessary language suggestion

### ISSUE THREAD

**Issue by thibaultmol** [WikidataComplete/Wikidata-Complete-Gadget#43]
It suggests a https://www.wikidata.org/wiki/Property:P407 statement when the item already has https://wikidata.org/wiki/Property:P364
Ex:
https://wikidata.org/wiki/Q1249131

**Comment by lalit97** [comment]
Hopefully, @D063520 will have some suggestions on it

**Comment by D063520** [comment]
Hi,

there are two point here:

1) wikidata complete makes a connection between a data donator and a user who approves the statement. Following your comment we decided to add a textual feedback so that you can inform the data donator directly about issues like this

2) in this case we are also donating this statement. Your point is completely right and we decided to remove from television series statements about "language of work" (P407).

Salut
D063520

@lalit97: can you please directly take care about point 2?

**Comment by lalit97** [comment]
> @lalit97: can you please directly take care about point 2?

sure @D063520 I will write a fix for point 2 soon and post an update here.

**Comment by lalit97** [comment]
Hi @thibaultmol  

We have removed data from our backend which was suggesting users to add Items with property `P407` even when the Wikidata entity already has property `P364`.

This will fix the issue. Thanks for reporting once again!

**Comment by lalit97** [comment]
@D063520 I have fixed point 2 as per our discussion. 

I have created https://github.com/WikidataComplete/Wikidata-Complete-Gadget/issues/45 for tracking point 1 

So we can close this once @thibaultmol reviews and confirms the resolution.
